### ISSUE TITLE
Script error on server start - index a nil value (job)

### ISSUE THREAD

**Issue by ChickenDipper1** [Redline-Studios/rs-frontdesk#5]
I get this error in the console when the server is started, the script will only work if manually restarted once logged in as a player.

`
Error loading script client/cl_main.lua in resource rs-frontdesk: @rs-frontdesk/client/cl_main.lua:3: attempt to index a nil value (field 'job')

`

**Comment by xThrasherrr** [comment]
Resolved:
https://github.com/Redline-Studios/rs-frontdesk/commit/e2b0f76538f00817f02eefecd2c641269dd3fd92
